baseurl = "https://www.olivierfredon.com"
title = "Olivier Fredon - Graphiste, Web designer et intégrateur freelance basé entre Agen et Villeneuve-sur-Lot (Lot-et-Garonne 47)"
languageCode = "fr"
theme = "curiosity"

pluralizeListTitles = false
enableInlineShortcodes = true

[params]
    author = "Olivier Fredon"
    pseudo = "the2ne"
    description = "Olivier Fredon - Designer et concepteur Web freelance: communication, graphisme Print, Web & UI Design, intégration, gestion de projet. Basé dans le Lot-et-Garonne (47) entre Agen et Villeneuve-sur-Lot."
    logo = "https://www.olivierfredon.com/images/logo.jpg"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "mailto:contact@olivierfredon.com"
    weight = 2
